### ISSUE TITLE
django 1.10 : AttributeError: 'module' object has no attribute 'SubfieldBase'

### ISSUE THREAD

**Issue by whaleforever** [makinacorpus/django-screamshot#43]
I got this error when using screamshot on django 1.10, it seems it has been deprecated.

is there a solution for this?

**Comment by ebrehault** [comment]
we check and fix ASAP

**Comment by gmunozc** [comment]
Install the master version, I made some fixes and it works for me in django 1.10

`pip install git+https://github.com/makinacorpus/django-screamshot -U`

**Comment by ebrehault** [comment]
@gmunozc thank you for your PR by the way :)

**Comment by whaleforever** [comment]
ah thanks

**Comment by gmunozc** [comment]
no problem, let me know if this works for you

**Comment by whaleforever** [comment]
sorry a little bit late, 
when I tried it as suggested by @gmunozc  it still throw an error, I fetch the master version:

```
Unhandled exception in thread started by <function wrapper at 0x7fee148fed70>
Traceback (most recent call last):
  File "/home/whale/.virtualenvs/rudybianco2/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/whale/.virtualenvs/rudybianco2/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/whale/.virtualenvs/rudybianco2/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/whale/.virtualenvs/rudybianco2/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/whale/.virtualenvs/rudybianco2/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/whale/.virtualenvs/rudybianco2/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/whale/.virtualenvs/rudybianco2/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/whale/.virtualenvs/rudybianco2/local/lib/python2.7/site-packages/screamshot/models.py", line 18, in <module>
    from timedelta.fields import TimedeltaField
  File "/home/whale/.virtualenvs/rudybianco2/local/lib/python2.7/site-packages/timedelta/__init__.py", line 11, in <module>
    from .fields import TimedeltaField
  File "/home/whale/.virtualenvs/rudybianco2/local/lib/python2.7/site-packages/timedelta/fields.py", line 18, in <module>
    class TimedeltaField(six.with_metaclass(models.SubfieldBase, models.Field)):
AttributeError: 'module' object has no attribute 'SubfieldBase'
```

the problem is timedeltafield still using `SubfieldBase`, I guess the only solution either you guys support the timedetlafield, or stop using it.

**Comment by gmunozc** [comment]
@whaleforever  i checked well and you're right.

I have made the corrections, you can use this command to install it while they approve the correction

`pip install git+https://github.com/gmunozc/django-screamshot`

You can also check the version tests in this link

https://travis-ci.org/makinacorpus/django-screamshot/builds/202829330

regards
